.TH MACHINERY 7 "April 2011" "Machinery 0\&.0\&.0" "Machinery Manual"
.
.SH NAME
Machinery \- toolchain machinery for code generation
.
.SH DESCRIPTION
Toolchain machinery for compilers, code generators, assemblers, linkers, and
emulators.
.
.SH BUGS
Please report bugs to the mailing list at \fB<machinery@googlegroups.com>\fP
.
.SH AUTHOR
Arto Bendiken <arto@bendiken.net>
.
.SH SEE ALSO
.BR libmachinery (3)
